require "minitest/autorun"
require "minitest/rg"
require "sinatra/activerecord"
require_relative "../app/models/demon.rb"
require_relative "../app/models/division.rb"
require_relative "../app/models/soul.rb"